### PR TITLE
fix warnings

### PR DESCRIPTION
**Pull request by hathach**
warning: taking address of packed member of 'directoryEntry' may result
in an unaligned pointer value [-Waddress-of-packed-member]

### CODE REVIEW

**Comment by ladyada** [comment]
do you want to switch this over to Actions instead of Travis? the upstream has ceased development and will not take PRs so it's ok if we diverge

**Comment by hathach** [comment]
@ladyada yeah, we can switch to action, upstream actually switch to use version 2 
https://github.com/greiman/SdFat/commits/master
which is rather active recently. At the time we are porting it is in the migration between v1 to v2. Maybe later on we could try to see if it is possible get some of our fix (e.g FAT12 with 2 FAT tables ) and other fixes, spidma merged to upstream. Anyway, I will add action as separate PR in the meanwhile

**Comment by ladyada** [comment]
yes at the time we last looked, v2 was not ready for use

**Comment by hathach** [comment]
> yes at the time we last looked, v2 was not ready for use

Ok, will definitely add action and then keep an eye on it later. There is no point to got merge to v1 at the moment though.

**Comment by brentru** [comment]
@hathach  Hi - what's the status of this PR? I'm building another library that depends on SdFat and is throwing #warnings from this lib.

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
this should still get actions but merging since brent want to use!

**Comment by hathach** [comment]
ah right, sorry, I totally forgot about this. will submit an separate PR for ci.

**Comment by brentru** [comment]
@hathach  There's no place for issues on this repo.. I'm still getting a _lot_ of warnings when compiling this library with `xtensa-esp32s2-elf-gcc` for the funhouse platform. 

Here's the output resulting from arduino-cli using the `ReadWrite` example for this library: https://gist.github.com/brentru/25fd2051c17c5e328c2d36a47b4ce248

**Comment by hathach** [comment]
@brentru it is due to arduino-esp core also defined symbol for those fileop such as `O_RDONLY, O_WRONLY` etc ... which is also defined by SdFat. I am not sure what is the best fix for this.

**Comment by brentru** [comment]
That sounds like it'd work, esp. if it's mostly redefined symbols. For now, I'm going to add a `.funhouse.skip` file into the workflow which is stalling due to these warnings.

Let me know when it's fixed and I'll try re-running the workflow.

**Pull request merged**
